// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Session_8____EFC_scaffolding.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Addresses = new HashSet<Address>();
            Emails = new HashSet<Email>();
            PhoneNumbers = new HashSet<PhoneNumber>();
        }

        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
    }
}