// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Session_7___Aflevering___DA;

#nullable disable

namespace Session_7___Aflevering___DA.Migrations
{
    [DbContext(typeof(VaregruppeDbContext))]
    [Migration("20240317091041_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Session_7___Aflevering___Models.Varer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StockAmount")
                        .HasColumnType("int");

                    b.Property<int>("VaregruppeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VaregruppeId");

                    b.ToTable("Varer");
                });

            modelBuilder.Entity("Session_7___Aflevering___Models.Varegruppe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Varegruppe");
                });

            modelBuilder.Entity("Session_7___Aflevering___Models.Varer", b =>
                {
                    b.HasOne("Session_7___Aflevering___Models.Varegruppe", "Varegruppe")
                        .WithMany("Varer")
                        .HasForeignKey("VaregruppeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Varegruppe");
                });

            modelBuilder.Entity("Session_7___Aflevering___Models.Varegruppe", b =>
                {
                    b.Navigation("Varer");
                });
#pragma warning restore 612, 618
        }
    }
}
