// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Session_8___test.Models
{
    public partial class Email
    {
        public int EmailId { get; set; }
        public int? EmployeeId { get; set; }
        public string Email1 { get; set; }

        public virtual Employee Employee { get; set; }
    }
}