// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Session_8___test.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Session_8___test.Models
{
    public partial class EmployeeTestContext
    {
        private IEmployeeTestContextProcedures _procedures;

        public virtual IEmployeeTestContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EmployeeTestContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IEmployeeTestContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class EmployeeTestContextProcedures : IEmployeeTestContextProcedures
    {
        private readonly EmployeeTestContext _context;

        public EmployeeTestContextProcedures(EmployeeTestContext context)
        {
            _context = context;
        }
    }
}
